2018-12-03 15:13:40,696 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:13:40,698 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:13:40,700 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:13:40,701 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:13:40,701 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:13:40,702 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:13:40,726 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:13:40,726 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:13:40,727 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:13:42,369 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 15:13:43,442 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 15:13:44,397 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 15:13:51,753 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 15:13:51,788 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:13:51,914 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:13:51,915 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:13:51,916 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:28:17,795 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:28:17,797 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:28:17,799 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:28:17,800 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:28:17,800 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:28:17,801 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:28:17,802 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:28:17,803 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:29:39,513 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:29:39,515 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:29:39,516 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:29:39,518 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:29:39,519 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:29:39,520 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:29:39,521 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:29:39,521 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:30:14,840 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:30:14,855 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:30:14,856 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:30:14,858 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:30:14,858 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:30:14,860 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:30:14,861 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:30:14,862 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:32:59,699 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:32:59,701 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:32:59,704 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:32:59,704 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:32:59,705 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:32:59,707 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:32:59,707 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:32:59,708 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:34:20,196 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:34:20,198 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:34:20,198 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:34:20,199 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:34:20,199 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:34:20,200 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:34:20,201 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:34:20,202 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:35:14,865 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:35:14,874 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:35:14,875 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:35:14,879 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:35:14,879 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:35:14,888 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:35:14,893 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:35:14,894 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:41:15,853 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:41:15,855 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:41:15,856 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:41:15,856 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:41:15,857 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:41:15,859 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:41:15,862 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:41:15,863 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:41:15,864 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:41:18,065 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 15:41:19,211 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 15:41:20,787 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 15:41:30,232 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 15:41:30,244 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:41:30,370 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:41:30,370 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:41:30,371 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:47:41,179 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:47:41,181 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:47:41,181 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:47:41,182 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:47:41,182 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:47:41,184 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:47:41,187 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:47:41,188 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:48:56,346 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:48:56,348 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:48:56,348 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:48:56,349 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:48:56,349 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:48:56,350 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:48:56,350 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:48:56,351 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:48:56,351 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:49:56,908 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:49:56,910 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:49:56,911 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:49:56,912 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:49:56,912 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:49:56,913 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:49:56,913 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:49:56,914 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:49:56,915 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:49:56,924 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:49:57,100 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:49:57,101 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:49:57,101 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:51:10,254 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:51:10,256 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:51:10,257 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:51:10,257 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:51:10,257 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:51:10,258 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:51:10,258 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:51:10,259 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:51:10,260 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:51:10,290 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:51:10,463 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:51:10,464 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:51:10,464 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:52:58,477 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:52:58,478 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:52:58,478 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:53:54,858 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:53:54,859 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:53:54,859 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:54:41,738 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:54:41,739 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:54:41,739 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:55:47,525 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:55:47,527 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:55:47,527 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:55:47,529 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:55:47,530 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:55:47,535 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:55:47,536 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:55:47,537 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:55:47,538 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:55:47,555 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:55:47,723 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:55:47,724 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:55:47,725 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:56:48,063 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:56:48,065 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:56:48,065 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:56:48,066 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:56:48,066 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:56:48,067 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:56:48,067 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:56:48,067 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:56:48,068 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:56:48,075 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:56:48,230 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:56:48,230 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:56:48,231 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:56:48,292 - compareFilesUtils.py:[35] - [INFO] - E:\TestPlatform\Uao\AutoUao\results\inePersonInput.json and E:\TestPlatform\Uao\AutoUao\results\inePersonOutput.json ,
 Two files has 20 differents .
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] line are different 
2018-12-03 15:58:01,355 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:58:01,358 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 15:58:01,360 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 15:58:01,360 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\results] successed! 
2018-12-03 15:58:01,361 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 15:58:01,362 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:58:01,363 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:58:01,363 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:58:01,364 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 15:58:01,371 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 15:58:01,524 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 15:58:01,524 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 15:58:01,525 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 15:58:01,587 - compareFilesUtils.py:[35] - [INFO] - E:\TestPlatform\Uao\AutoUao\results\inePersonInput.json and E:\TestPlatform\Uao\AutoUao\results\inePersonOutput.json ,
 Two files has 20 differents .
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] line are different 
2018-12-03 16:01:48,025 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 16:01:48,026 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 16:01:48,026 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 16:01:48,027 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 16:01:48,027 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 16:01:48,028 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:01:48,028 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:01:48,028 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:01:48,029 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 16:01:48,035 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 16:01:48,179 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:01:48,180 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:01:48,180 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:01:48,239 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json ,
 Two files has 20 differents .
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] line are different 
2018-12-03 16:02:10,150 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 16:02:10,153 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 16:02:10,155 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 16:02:10,156 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 16:02:10,157 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 16:02:10,159 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:02:10,160 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:02:10,160 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:02:10,161 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 16:02:10,169 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 16:02:10,525 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:02:10,526 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:02:10,526 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:03:38,411 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:03:38,412 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:03:38,412 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:04:44,714 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:04:44,714 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:04:44,715 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:05:37,272 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:05:37,273 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:05:37,273 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:06:00,697 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:06:00,698 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:06:00,698 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:08:30,425 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:08:30,425 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:08:30,426 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:08:43,365 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:08:43,366 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:08:43,367 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:09:08,881 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:09:08,882 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:09:08,882 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:09:18,993 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:09:18,994 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:09:18,994 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:09:27,054 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:09:27,055 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:09:27,055 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:12:06,825 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:12:06,825 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:12:06,825 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:12:18,873 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:12:18,873 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:12:18,875 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:17:14,737 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:17:14,738 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:17:14,738 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:18:32,059 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:18:32,060 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:18:32,060 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:18:46,283 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:18:46,284 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:18:46,284 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:20:23,051 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:20:23,051 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:20:23,052 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:21:14,084 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:21:14,084 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:21:14,085 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:21:27,946 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:21:27,946 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:21:27,947 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:21:41,485 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:21:41,486 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:21:41,486 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:22:18,448 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:22:18,449 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:22:18,449 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:22:32,156 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:22:32,157 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:22:32,157 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:22:46,410 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:22:46,411 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:22:46,411 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:22:53,449 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:22:53,449 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:22:53,450 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:23:20,629 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:23:20,630 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:23:20,631 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:28:24,643 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:28:24,644 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:28:24,645 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:29:31,885 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:29:31,885 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:29:31,886 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:29:49,396 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:29:49,396 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:29:49,397 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:30:06,451 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:30:06,452 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:30:06,452 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:31:12,936 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:31:12,937 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:31:12,938 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:31:22,168 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:31:22,169 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:31:22,169 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:31:31,850 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:31:31,851 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:31:31,851 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:32:37,408 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:32:37,408 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:32:37,408 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:32:48,609 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:32:48,610 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:32:48,610 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:32:56,149 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:32:56,150 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:32:56,151 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:33:06,888 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:33:06,889 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:33:06,889 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:33:36,813 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:33:36,813 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:33:36,814 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:33:46,500 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:33:46,500 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:33:46,501 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:34:06,564 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:34:06,564 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:34:06,565 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:35:15,983 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:35:15,984 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:35:15,984 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:36:10,612 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:36:10,612 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:36:10,613 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:36:18,601 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:36:18,602 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:36:18,602 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:37:45,602 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:37:45,603 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:37:45,605 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:39:22,276 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:39:22,277 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:39:22,278 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:41:12,910 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:41:12,912 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:41:12,914 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:53:53,203 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:53:53,203 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:53:53,204 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:55:58,849 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 16:55:58,859 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 16:55:58,860 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 16:55:58,860 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 16:55:58,861 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 16:55:58,863 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:55:58,863 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:55:58,864 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:55:58,865 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 16:56:03,498 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 16:56:04,362 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 16:56:05,184 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 16:56:12,868 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 16:56:12,878 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 16:56:12,987 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 16:56:12,988 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 16:56:12,988 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 16:56:13,055 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json ,
 Two files has 5 differents .
 [8, 9, 18, 19, 20] line are different 
2018-12-03 17:00:05,032 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:00:05,034 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 17:00:05,035 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 17:00:05,035 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:00:05,036 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 17:00:05,037 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:00:05,037 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:00:05,038 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:00:05,038 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 17:00:06,366 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 17:00:07,227 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 17:00:07,835 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 17:00:15,713 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 17:00:15,716 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 17:00:15,815 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:00:15,815 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:00:15,816 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:00:15,871 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json ,
 Two files has 5 differents .
 [8, 9, 18, 19, 20] line are different 
2018-12-03 17:01:42,570 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:01:42,573 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 17:01:42,573 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 17:01:42,574 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:01:42,574 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 17:01:42,575 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:01:42,576 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:01:42,576 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:01:42,577 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 17:01:44,220 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 17:01:44,829 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 17:01:45,468 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 17:01:53,021 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 17:08:04,762 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:08:04,765 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 17:08:04,766 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 17:08:04,767 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:08:04,768 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 17:08:04,769 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:08:04,775 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:08:04,776 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:08:04,777 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 17:08:06,583 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 17:08:07,334 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 17:08:07,902 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 17:08:15,583 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 17:08:15,592 - xml2jsonUtils.py:[69] - [INFO] - person xml2json done !!!
2018-12-03 17:08:15,701 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:08:15,702 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:08:15,702 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:08:15,770 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json ,
 Two files has 3 differents .
 [18, 19, 20] line are different 
2018-12-03 17:29:29,271 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:29:29,272 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 17:29:29,273 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 17:29:29,273 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:29:29,273 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 17:29:29,274 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:29:29,274 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:29:29,275 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:29:29,275 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 17:29:30,434 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 17:29:31,047 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 17:29:31,879 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 17:29:39,492 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 17:29:39,506 - xml2jsonUtils.py:[70] - [INFO] - person xml2json done !!!
2018-12-03 17:29:39,614 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:29:39,615 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:29:39,615 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:29:39,674 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json ,
 Two files has 3 differents .
 [4, 8, 9] line are different 
2018-12-03 17:30:28,143 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:30:28,145 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 17:30:28,146 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 17:30:28,146 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 17:30:28,147 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 17:30:28,147 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:30:28,148 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:30:28,149 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:30:28,150 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 17:30:29,960 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 17:30:30,599 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 17:30:31,427 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 17:30:38,999 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 17:30:39,010 - xml2jsonUtils.py:[70] - [INFO] - person xml2json done !!!
2018-12-03 17:30:39,203 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 17:30:39,204 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 17:30:39,205 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 17:30:39,305 - compareFilesUtils.py:[29] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json , Two files are same !
2018-12-03 18:00:33,222 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:00:33,223 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:00:33,224 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:00:33,224 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:00:33,224 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:00:33,225 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:00:33,225 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:00:33,226 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:00:33,228 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\InePersonAccount] successed! 
2018-12-03 18:00:34,860 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 18:00:35,460 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 18:00:36,087 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\InePersonAccount\cfmmc_N_20181203_00000012.xml, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 18:00:43,450 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 18:00:43,458 - xml2jsonUtils.py:[70] - [INFO] - person xml2json done !!!
2018-12-03 18:00:43,610 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:00:43,611 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:00:43,611 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:00:43,680 - compareFilesUtils.py:[29] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\inePersonOutput.json , Two files are same !
2018-12-03 18:17:30,409 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:17:30,410 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:17:30,411 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:17:30,411 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:17:30,412 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:17:30,412 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:17:30,413 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:17:30,414 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:17:30,415 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount] successed! 
2018-12-03 18:17:32,078 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 18:17:33,255 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 18:17:34,124 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount\cfmmc_N_20181203_00000002.zip, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 18:17:42,211 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 18:17:42,221 - xml2jsonUtils.py:[136] - [INFO] - organ xml2json done !!!
2018-12-03 18:17:42,333 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:17:42,334 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:17:42,334 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:20:43,029 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:20:43,030 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:20:43,030 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:20:43,031 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:20:43,031 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:20:43,032 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:20:43,032 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:20:43,033 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:20:43,033 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount] successed! 
2018-12-03 18:20:44,397 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 18:20:45,005 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 18:20:45,740 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount\cfmmc_N_20181203_00000012.zip, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 18:20:53,994 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 18:20:53,999 - xml2jsonUtils.py:[136] - [INFO] - organ xml2json done !!!
2018-12-03 18:20:54,109 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:20:54,110 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:20:54,110 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:27:14,035 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:27:14,036 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:27:14,037 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:27:14,037 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:27:14,037 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:27:14,040 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:27:14,040 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:27:14,041 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:27:14,041 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount] successed! 
2018-12-03 18:27:15,381 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 18:27:16,155 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 18:27:17,015 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount\cfmmc_N_20181203_00000012.zip, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 18:27:24,159 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 18:27:24,171 - xml2jsonUtils.py:[136] - [INFO] - organ xml2json done !!!
2018-12-03 18:27:24,274 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:27:24,275 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:27:24,275 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:29:15,974 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:29:15,977 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:29:15,985 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:29:15,986 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:29:15,989 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:29:15,995 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:29:15,999 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:29:15,999 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:29:16,000 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount] successed! 
2018-12-03 18:29:17,656 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 18:29:18,483 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 18:29:19,147 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount\cfmmc_N_20181203_00000012.zip, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 18:29:27,360 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 18:29:27,416 - xml2jsonUtils.py:[136] - [INFO] - organ xml2json done !!!
2018-12-03 18:29:27,542 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:29:27,543 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:29:27,543 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:29:27,629 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\ineOrganInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\ineOrganOutput.json ,
 Two files has 1 differents .
 [11] line are different 
2018-12-03 18:44:27,978 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:44:27,980 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:44:27,980 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:44:27,981 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:44:27,981 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:44:27,982 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:44:27,982 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:44:27,982 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:44:27,983 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount] successed! 
2018-12-03 18:44:29,023 - uao.py:[60] - [INFO] - Get Uao Remote Service Ip : 172.24.118.3
2018-12-03 18:44:29,607 - sshUtils.py:[73] - [INFO] - cd /home/uapp/services/uao_ineuao1/recv/ ; rm -r *20181203*
2018-12-03 18:44:30,792 - sshUtils.py:[89] - [INFO] - Uploading file :E:\TestPlatform\Uao\AutoUao\data\IneOrganAccount\cfmmc_N_20181203_00000012.zip, to 172.24.118.3 : /home/uapp/services/uao_ineuao1/recv/ ,Uploading file success
2018-12-03 18:44:40,077 - uao.py:[80] - [INFO] - excu IneUao !
20181203
ine

excu done

2018-12-03 18:44:40,096 - xml2jsonUtils.py:[136] - [INFO] - organ xml2json done !!!
2018-12-03 18:44:40,227 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:44:40,227 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:44:40,228 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:44:40,308 - compareFilesUtils.py:[35] - [INFO] - E:\\TestPlatform\\Uao\\AutoUao\\results\ineOrganInput.json and E:\\TestPlatform\\Uao\\AutoUao\\results\ineOrganOutput.json ,
 Two files has 1 differents .
 [11] line are different 
2018-12-03 18:51:44,510 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:51:44,512 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:51:44,512 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:51:44,513 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:51:44,513 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:51:44,514 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:51:44,514 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:51:44,514 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:51:54,136 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:51:54,139 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:51:54,139 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:51:54,140 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:51:54,141 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:51:54,144 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:51:54,145 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:51:54,146 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:52:23,251 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:52:23,252 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:52:23,253 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:52:23,253 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:52:23,253 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:52:23,254 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:52:23,259 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:52:23,261 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:52:47,261 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:52:47,263 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:52:47,263 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:52:47,264 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:52:47,264 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:52:47,265 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:52:47,265 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:52:47,265 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:54:42,223 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:54:42,225 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:54:42,225 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:54:42,226 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:54:42,226 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:54:42,227 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:54:42,227 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:54:42,228 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:55:36,840 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:55:36,842 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:55:36,843 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:55:36,844 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:55:36,844 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:55:36,847 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:55:36,848 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:55:36,849 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 18:58:00,482 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:58:00,484 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 18:58:00,485 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 18:58:00,485 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 18:58:00,486 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 18:58:00,487 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 18:58:00,487 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 18:58:00,488 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
2018-12-03 19:00:17,389 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 19:00:17,390 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_uao1/recv/] successed! 
2018-12-03 19:00:17,391 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [/home/uapp/services/uao_ineuao1/recv/] successed! 
2018-12-03 19:00:17,391 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [E:\\TestPlatform\\Uao\\AutoUao\\results] successed! 
2018-12-03 19:00:17,391 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.2] successed! 
2018-12-03 19:00:17,392 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [party] successed! 
2018-12-03 19:00:17,393 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [oracle] successed! 
2018-12-03 19:00:17,394 - doconfiniUtils.py:[35] - [INFO] - read config.ini value [172.24.118.8:1521/tbdb] successed! 
